### ISSUE TITLE
Error: Column start (15) greater than line length (13)

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-stylelint#166]
The very first time I tried to use this:
````
Error: Column start (15) greater than line length (13)
    at Object.rangeFromLineNumber (/Users/stevelombardi/.atom/packages/linter-stylelint/node_modules/atom-linter/lib/index.js:194:11)
    at /Users/stevelombardi/.atom/packages/linter-stylelint/node_modules/lazy-req/index.js:20:26
    at createRange (/Users/stevelombardi/.atom/packages/linter-stylelint/lib/index.js:41:10)
    at /Users/stevelombardi/.atom/packages/linter-stylelint/lib/index.js:80:14
    at Array.map (native)
    at stylelint.lint.then.error.type (/Users/stevelombardi/.atom/packages/linter-stylelint/lib/index.js:76:38)
````

I had to disable it.

**Comment by Arcanemagus** [comment]
Can you please share your `stylelint` configuration, as well as the file you were editing (in a state that triggers that warning!).

This is almost certainly a bug in `stylelint` itself, so tracking this down will help everyone :wink:.

**Comment by davidtheclark** [comment]
@smlombardi Are you on Windows? There is a known Windows bug in some rules that might cause this: https://github.com/stylelint/stylelint/issues/1081. We are trying to address it. Figuring out which rules cause the problem will speed up the fix. Thank.s

**Comment by Arcanemagus** [comment]
@davidtheclark The paths in the stack trace are from OSX I believe, but they might still be editing a `CRLF` file.

**Comment by davidtheclark** [comment]
True.

**Comment by smlombardi** [comment]
On OSX.  File uses Unix LF.  I don't have a stylelint config yet, I set the package to use Standard for starters.  I will try and get the exact file I tested on.

**Comment by smlombardi** [comment]
I don't know if this is related, but I installed it on my other MBP and when I open a scss file and try to force an error by deleting a semicolon I get this

![screen shot 2016-04-20 at 6 09 56 pm](https://cloud.githubusercontent.com/assets/835148/14692134/3e18f420-0723-11e6-830f-131aa4ca664e.png)

**Comment by davidtheclark** [comment]
Huh ... I just installed the latest `linter-stylelint` version, use stylelint-config-standard in my own config, and don't have the same Atom problems. Please double-check which versions of each part you are using.

**Comment by Arcanemagus** [comment]
@smlombardi Without the files that are triggering these errors it's rather difficult to diagnose this. Whenever you see an error pop up can you save the file in that state and then attach it here?

If the files are unable to be shared publicly you can direct message them to me on [Atom's Slack](http://atom-slack.herokuapp.com/).

**Comment by smlombardi** [comment]
The file above is http://cl.ly/00450N331f24/_leftMenu.scss

This is Atom 1.8b2.  Here's the sequence:

![apr-20-2016 18-24-40](https://cloud.githubusercontent.com/assets/835148/14692560/ff69411e-0725-11e6-8939-04536c93a83b.gif)

**Comment by Arcanemagus** [comment]
Looks like that later one is a bug in `stylelint`:
![image](https://cloud.githubusercontent.com/assets/427137/14693000/2128edce-0710-11e6-901e-11a13e9ed537.png)

Can you report that on [their issue tracker](https://github.com/stylelint/stylelint/issues) to get that tracked down further? Here is a file that contains a reproduceable environment: [linter-stylelint_GH166.zip](https://github.com/AtomLinter/linter-stylelint/files/228994/linter-stylelint_GH166.zip)

If you have a file that can reproduce the first issue we can start the process of tracking that down as well!

**Comment by davidtheclark** [comment]
@smlombardi I think the "Unexpected space" issue is being caused by a dependency of stylelint stumbling on the nested selectors. I'll try to see what can be done.

**Comment by davidtheclark** [comment]
Actually, on looking closer, I'd suggest that this "Unexpected space" thing might not be a bug at all. I believe that without that semicolon you're providing is invalid, unparseable syntax, so it's going to error.

**Comment by smlombardi** [comment]
Well, isn't a missing semicolon a common programmer error?  scss-lint handles it, reports the error without an error dialog.  For that reason I frequently use deleting a semicolon as a quick way to test that a linter is properly installed on my part.

**Comment by smlombardi** [comment]
http://cl.ly/1X2R2Q1C0p36/documentation.scss  is a file that gives the error originally reported (at least on my work MBP).  I deleted the semicolon at the end of line 27.  stylelint and scss-lint report the error in the status bar correctly.  I put the semicolon **back** and I get

````
Error: Column start (4) greater than line length (2)
    at Object.rangeFromLineNumber (/Users/stevelombardi/.atom/packages/linter-htmlhint/node_modules/atom-linter/lib/index.js:194:11)
    at /Users/stevelombardi/.atom/packages/editorconfig/node_modules/lazy-req/index.js:20:26
    at createRange (/Users/stevelombardi/.atom/packages/linter-stylelint/lib/index.js:41:10)
    at /Users/stevelombardi/.atom/packages/linter-stylelint/lib/index.js:80:14
    at Array.map (native)
    at stylelint.lint.then.error.type (/Users/stevelombardi/.atom/packages/linter-stylelint/lib/index.js:76:38)
````

**Comment by Arcanemagus** [comment]
Marking this as closed since both bugs are in `stylelint` and have been reported there.

**Comment by smlombardi** [comment]
If this is fixed in stylelint 6.0.3, when does it get pulled into the Atom linter?

**Comment by Arcanemagus** [comment]
It's fixed in v6.1.0, which I'm just about to merge here :wink:.

**Comment by Arcanemagus** [comment]
FYI, the changelog lists when new versions of `stylelint` are included here.

**Comment by Arcanemagus** [comment]
@smlombardi I've just released v2.6.0 of this package which includes `stylelint` v6.1.0. This should fix that issue for you :wink:.

**Comment by smlombardi** [comment]
Outstanding!

**Comment by PhiLhoSoft** [comment]
Windows 7, Atom 1.7.2, atom-stylelint 2.6.0 (I uninstalled it and re-installed it just in case the upgrade went bad).
I still see the issue.

> Error: Column start (20) greater than line length (1)
>     at Object.rangeFromLineNumber (C:\Users\plhoste\.atom\packages\linter-eslint\node_modules\atom-linter\lib\index.js:194:11)
>     at C:\Users\plhoste\.atom\packages\linter-stylelint\node_modules\lazy-req\index.js:20:26
>     at createRange (C:/Users/plhoste/.atom/packages/linter-stylelint/lib/index.js:41:10)
>     at C:/Users/plhoste/.atom/packages/linter-stylelint/lib/index.js:80:14
>     at Array.map (native)
>     at stylelint.lint.then.error.type (C:/Users/plhoste/.atom/packages/linter-stylelint/lib/index.js:76:38)

This one appeared right after I installed (back) the package and went to a .scss file.

Actually, I could pinpoint what triggers it.
It appears as soon as I put a line comment in a .scss file, after a selector.
Line comments are harmless after variable declarations, or plain CSS declarations, but fatal after a selector.

I join a sample SCSS file and my config file, hoping you can reproduce it.
[Stylelint-issue.zip](https://github.com/AtomLinter/linter-stylelint/files/234707/Stylelint-issue.zip)

See the comment ` // Triggers the bug!`
Remove it, no problem. Paste it back, the error above appears after a second or two.

**Comment by smlombardi** [comment]
This still happens while editing a scss file...

![screen shot 2016-04-25 at 2 31 32 pm](https://cloud.githubusercontent.com/assets/835148/14794844/cb20a98e-0af3-11e6-8a30-25ac593006a4.jpg)

**Comment by Arcanemagus** [comment]
@smlombardi Does `stylelint@6.2.0` report the same thing?

@PhiLhoSoft as each of these errors can be caused by any number of things can you please file a new issue so we can track down your specific case of why `stylelint` is sending bad column data to `linter-stylelint`?

**Comment by PhiLhoSoft** [comment]
OK, no problem.
Even though my report is more related to the original issue that the latest reported by @smlombardi... :smile: 

For the record, I also saw these space errors, while typing a new rule (with 6.2.0), but was not able to reproduce it.

**Comment by smlombardi** [comment]
This is a real pain.  Every time I type a new rule in a selector, every character after I type the colon triggers an error.

![screen shot 2016-04-26 at 9 29 31 am](https://cloud.githubusercontent.com/assets/835148/14819758/925f3ca2-0b91-11e6-96c7-7a87ff9569f9.jpg)

**Comment by Arcanemagus** [comment]
@davidtheclark Is this a bug in `stylelint` that that message is being thrown back with no line? The only way that message should show is if the `stylelint` Promise throws an error, and that error has no line associated with it.

**Comment by davidtheclark** [comment]
It's worth raising in stylelint and seeing if we can reproduce it from the CLI. I think that what's happening is that postcss-selector-parser is throwing this error because it's running into some non-standard SCSS construct, that error is being thrown and Atom linter is just displaying it the way that it displays errors. I'd think that the error would be caught within the Promise, though, so I don't know exactly what's going on .... but chances our we may need to wrap usage of postcss-selector-parser in a try-catch or something to prevent this. We'll see.

**Comment by Arcanemagus** [comment]
It's being displayed [here](https://github.com/AtomLinter/linter-stylelint/blob/v2.7.0/lib/index.js#L101), within the `error` function of the promise. I'll file something on `stylelint` in a tiny bit.

**Comment by Arcanemagus** [comment]
Narrowed it down to `selector-type-case`, the above issue has all the details :wink:.
