### ISSUE TITLE
Could not find "stylelint-config-standard". Do you need a `configBasedir`?

### ISSUE THREAD

**Issue by paulrobertlloyd** [AtomLinter/linter-stylelint#68]
Hello,

According to the docs, I can set up my linting rules in my package.json, and extend a default config, like so:

```json
"stylelint": {
    "extends": "stylelint-config-standard",
    "rules": {
        "indentation": 4
    }
}
```

Yet when I do this, I get the following error:

*Could not find "stylelint-config-standard". Do you need a `configBasedir`?*

I tried using the same config, set via a .stylelintrc file, but got the same error. Am I doing something wrong? I’m using v1.10.2 of this package, with Atom v1.4.0.

Thanks,

Paul

**Comment by SeanHayes** [comment]
Same here.

**Comment by davidtheclark** [comment]
If you have a problem happening with stylelint that you can reproduce outside of Atom editor and the linter-stylelint problem, please file an issue with stylelint instead of here: https://github.com/stylelint/stylelint/issues. If the problem only occurs when linter-stylelint is involved, then the issue is appropriate here.

**Comment by SeanHayes** [comment]
Here's the issue I opened: https://github.com/stylelint/stylelint-config-standard/issues/4

**Comment by davidtheclark** [comment]
Cool, thanks @SeanHayes.

**Comment by paulrobertlloyd** [comment]
Okay, with this in mind, updated my config to point directly to the `stylelint-config-standard` module folder within the `linter-stylelint` package, like so:

```json
"stylelint": {
    "extends": "/Volumes/Macintosh/Users/paulrobertlloyd/.atom/packages/linter-stylelint/node_modules/stylelint-config-standard",
    "rules": {
        "indentation": 4
    }
}
```

But that’s not going to work across different machines. Should this package set the `configBasedir` value to the location of the package’s node_modules folder?

**Comment by Arcanemagus** [comment]
@paulrobertlloyd I think that this would be a duplicate of #51 if that's the case here. This is definitely something that should be moved towards as all the Node based linters _should_ be able to use the project based one (which would include getting the configuration from the project and not the plugin itself).

Is that the case here?

**Comment by paulrobertlloyd** [comment]
Hmmm, not really. I haven’t installed stylelint into my project, so I am relying on the version included within this plugin. The problem is (I think), that this plugin doesn’t appear to know where config presets are located. Does that make sense?

**Comment by Arcanemagus** [comment]
Sorry, forgot to respond here: Yes that makes sense, but that is exactly what #51 would solve :wink:.

**Comment by hkongm** [comment]
same problem

**Comment by Arcanemagus** [comment]
Okay, after working on a similar issue and with a greater understanding of how generating the config is done... this should be working.

@paulrobertlloyd and @hkongm can you provide an exact folder structure including where you have your configuration files, and what file you are linting when you see this issue?

**Comment by paulrobertlloyd** [comment]
I am still getting the same error. You can see my folder structure here: https://github.com/paulrobertlloyd/paulrobertlloyd.com (my .stylelintrc config file appears in the project root). I get this error if I add `"extends": "stylelint-config-standard"` to my config file, or check ‘Use standard’ in linter-stylelint’s settings.

**Comment by Arcanemagus** [comment]
@paulrobertlloyd `extends` is an array key, not a single element. Also do you have something installing `stylelint-config-standard` into your project?

If I clone your repository as it currently is (https://github.com/paulrobertlloyd/paulrobertlloyd.com/commit/65e71abf392d15e841616d1f7adb3dc7f437e89f), `linter-stylelint` works just fine, although it will only show fatal errors unless the "Use preset" is checked.

If I add `"extends": ["stylelint-config-standard"]` to your `.stylelintrc` **and** run `npm install stylelint-config-standard` in your project (since you have no `package.json`), everything works as expected as well.

I am unable to reproduce using your repository if everything is setup properly.

**Comment by ismay** [comment]
I've got the same error, but for `stylelint-selector-bem-pattern`:

<img width="491" alt="screen shot 2016-03-16 at 22 15 13" src="https://cloud.githubusercontent.com/assets/7355199/13829040/1d511732-ebc5-11e5-805a-b7b900f6a77f.png">

Code that resulted in this error can be found in this [branch](https://github.com/ismay/ismay.github.io/tree/lint-bem). 
  * [.stylelintrc](https://github.com/ismay/ismay.github.io/blob/lint-bem/.stylelintrc)
  * [package.json](https://github.com/ismay/ismay.github.io/blob/lint-bem/package.json)

**Comment by Arcanemagus** [comment]
@ismay You must be on an older version of the plugin, the latest version bundles `stylelint@^5.0.1` which throws errors about the (now) undefined rules in your configuration.

**Comment by ismay** [comment]
@Arcanemagus I am on 2.0.1, so that shouldn't be the problem. It can't be picking up the version from my `package.json` right? Because that's `"stylelint": "^4.4.0"`.

**Comment by Arcanemagus** [comment]
@ismay If you are supposedly on v2.0.1 of `linter-stylelint` then Atom didn't install the dependencies correctly, since that has a [minimum version](https://github.com/AtomLinter/linter-stylelint/blob/v2.0.1/package.json#L38) of v5.0.1 for the bundled `stylelint`, and that version is incompatible with the rules you have specified in your `.stylelintrc` file. Specifically you are extending `stylelint-config-suitcss`, which hasn't updated for `stylelint@^5.0.0` yet.

**Comment by Arcanemagus** [comment]
Ah, just saw that I was still on your `master` branch, I get the error you are seeing as well and will look into it (Without the `stylelint-selector-bem-pattern` though you would be hitting the `stylelint-config-suitcss` issues though...).

**Comment by Arcanemagus** [comment]
@ismay Looks like your issue is fixed in https://github.com/stylelint/stylelint/pull/913, which hasn't been released yet.

**Comment by Arcanemagus** [comment]
@hkongm Can you post the requested information?

**Comment by ismay** [comment]
@Arcanemagus You're right. That's why I'm installing stylelint 4 locally (and opened this [issue](https://github.com/suitcss/stylelint-config-suitcss/issues/14)). But that won't fix the incompatibility of those rules with linter-stylelint of course. Didn't know that stylelint used its own version of stylelint at the time.

But anyway, my reported error should then be fixed when pr #913 is released and used with linter-stylelint. Thanks for the quick replies!

**Comment by paulrobertlloyd** [comment]
I think regarding my original issue, this fixes everything for me. For projects where I don’t have stylelint installed (i.e. no node modules or package.json), I can check the ’use standard presets’ option in the package settings, and then everything will work as expected (whereas it didn’t before).

**Comment by Arcanemagus** [comment]
@paulrobertlloyd I figured, and as @hkongm hasn't responded in 10 days I'm going to mark this as closed.

@hkongm if you are still experiencing this problem please file a _new_ issue with the information requested [here](https://github.com/AtomLinter/linter-stylelint/issues/68#issuecomment-195710196) and we can diagnose what your issue is.

**Comment by gitanupam** [comment]
FYI: Alright, for those who end up Googling here with the same issue, here are the three ways to debug the error:"Could not find "stylelint-config-standard". Do you need a configBasedir?" 

1) add the absolute path as in [this](https://github.com/AtomLinter/linter-stylelint/issues/68#issuecomment-177324259) comment by @paulrobertlloyd.
2) If you don't want to change/extend the standard rules, you can do [this](https://github.com/AtomLinter/linter-stylelint/issues/68#issuecomment-197627139). I think the checkbox is called 'Use Standard' now (I think that should be checked by default though). Opened an issue [here](https://github.com/stylelint/stylelint-config-standard/issues/62) to check with folks. 
3) If you do want to change the rules (like I don't like mandating empty lines before comments), but don't want to put down absolute paths (like in (1) above) either, then just do `npm install stylelint-config-standard` as @Arcanemagus suggests [here](https://github.com/AtomLinter/linter-stylelint/issues/68#issuecomment-196398972) in your project's root folder and it will then find the rules to refer to.

**Comment by nottoseethesun** [comment]
@gitanupam  -  I tried #3 above and that did not work. However the similar solution of adding `stylelint-processor-styled-components` to my `package.json` (in `devDependencies`) did work.

**Comment by carlkenne** [comment]
I got this issue probably because my package.json is not in my root folder. Simply adding the full path: "./web/node_modules/stylelint-config-..." fixed it for me

**Comment by Arcanemagus** [comment]
@carlkenne Please follow https://github.com/AtomLinter/linter-stylelint/issues/357, the bug this issue is about was fixed long ago.

**Comment by gbpatil** [comment]
make sure you have downloaded all the dependencies. Run YARN or NPM Install and reverify. Error should go away.

**Comment by suretrust** [comment]
Just run 
```
npm install --save-dev stylelint stylelint-scss stylelint-config-standard stylelint-csstree-validator
```
or 
```
yarn add stylelint stylelint-scss stylelint-config-standard stylelint-csstree-validator
``` 
as the case may be.

**Comment by evanjmg** [comment]
I made a custom library to host my index.js file to extend and I am getting this. I didn't prefix with stylelint - would that cause it? I get the same error as above.

**Comment by AmaliaGM** [comment]
> Just run
> 
> ```
> npm install --save-dev stylelint stylelint-scss stylelint-config-standard stylelint-csstree-validator
> ```
> 
> or
> 
> ```
> yarn add stylelint stylelint-scss stylelint-config-standard stylelint-csstree-validator
> ```
> 
> as the case may be.

This worked! Thanks so much!

**Comment by JuanmaMenendez** [comment]
The solution for me was adding the overrides code to the config

```
module.exports = {
	overrides: [
		{
			files: ["**/*.scss"],
			customSyntax: "postcss-scss"
		}
	],
	rules: {...	},
}
```
